<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;

class SiswaTableSeeder extends Seeder
{

    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {
        

        \DB::table('siswa')->delete();
        
        \DB::table('siswa')->insert(array (
            0 => 
            array (
                'NOMOR_INDUK' => '2282',
                'ID_ORTU' => 'WM001',
                'ID_SEKOLAH' => 'SCH0001',
                'NAMA_SISWA' => 'Abrian Firman Radityya',
                'NISN_SISWA' => '111695897',
                'JENIS_KELAMIN' => 'L',
                'TEMPAT_TANGGAL_LAHIR' => 'Badung, 16 Desember 2013',
                'AGAMA' => 'Islam',
                'ANAK_KE' => '1',
                'STATUS_DALAM_KELUARGA' => 'Anak Kandung',
                'ALAMAT' => 'Jl Bunguran 45',
                'TELEPON' => '',
                'FOTO' => '',
                'DITERIMA_DIKELAS' => 'SATU',
                'TANGGAL_DITERIMA_DIKELAS' => '2018-07-16',
            ),
            1 => 
            array (
                'NOMOR_INDUK' => '2283',
                'ID_ORTU' => 'WM002',
                'ID_SEKOLAH' => 'SCH0002',
                'NAMA_SISWA' => 'Achmad Fachrie Al Azizi',
                'NISN_SISWA' => '111245000',
                'JENIS_KELAMIN' => 'L',
                'TEMPAT_TANGGAL_LAHIR' => 'Tangerang, 5 September 2011',
                'AGAMA' => 'Islam',
                'ANAK_KE' => '2',
                'STATUS_DALAM_KELUARGA' => 'Anak Kandung',
                'ALAMAT' => 'Jl Tl Kumai Tmr 67',
                'TELEPON' => '',
                'FOTO' => '',
                'DITERIMA_DIKELAS' => 'SATU',
                'TANGGAL_DITERIMA_DIKELAS' => '2018-07-16',
            ),
            2 => 
            array (
                'NOMOR_INDUK' => '2285',
                'ID_ORTU' => 'WM003',
                'ID_SEKOLAH' => 'SCH0003',
                'NAMA_SISWA' => 'Ahmad Dwi Setyo Wairoy',
                'NISN_SISWA' => '128830900',
                'JENIS_KELAMIN' => 'L',
                'TEMPAT_TANGGAL_LAHIR' => 'Cirebon, 12 September 2013',
                'AGAMA' => 'Islam',
                'ANAK_KE' => '3',
                'STATUS_DALAM_KELUARGA' => 'Anak Kandung',
                'ALAMAT' => 'Jl Rajawali 26',
                'TELEPON' => '',
                'FOTO' => '',
                'DITERIMA_DIKELAS' => 'SATU',
                'TANGGAL_DITERIMA_DIKELAS' => '2018-07-16',
            ),
            3 => 
            array (
                'NOMOR_INDUK' => '2287',
                'ID_ORTU' => 'WM004',
                'ID_SEKOLAH' => 'SCH0004',
                'NAMA_SISWA' => 'Ahnaf Haris Zuhayr Al-Farizi',
                'NISN_SISWA' => '114104102',
                'JENIS_KELAMIN' => 'L',
                'TEMPAT_TANGGAL_LAHIR' => 'Surabaya, 27 November 2013',
                'AGAMA' => 'Islam',
                'ANAK_KE' => '2',
                'STATUS_DALAM_KELUARGA' => 'Anak Kandung',
                'ALAMAT' => 'Jl Perak Tmr 120',
                'TELEPON' => '',
                'FOTO' => '',
                'DITERIMA_DIKELAS' => 'SATU',
                'TANGGAL_DITERIMA_DIKELAS' => '2018-07-16',
            ),
            4 => 
            array (
                'NOMOR_INDUK' => '2289',
                'ID_ORTU' => 'WM005',
                'ID_SEKOLAH' => 'SCH0005',
                'NAMA_SISWA' => 'Aisyah Ayudia Inara',
                'NISN_SISWA' => '124530532',
                'JENIS_KELAMIN' => 'P',
                'TEMPAT_TANGGAL_LAHIR' => 'Surabaya, 9 Mei 2012',
                'AGAMA' => 'Islam',
                'ANAK_KE' => '1',
                'STATUS_DALAM_KELUARGA' => 'Anak Kandung',
                'ALAMAT' => 'Jl Kalikepiting 163-U',
                'TELEPON' => '',
                'FOTO' => '',
                'DITERIMA_DIKELAS' => 'SATU',
                'TANGGAL_DITERIMA_DIKELAS' => '2018-07-16',
            ),
            5 => 
            array (
                'NOMOR_INDUK' => '2292',
                'ID_ORTU' => 'WM006',
                'ID_SEKOLAH' => 'SCH0004',
                'NAMA_SISWA' => 'Amira Prisa Areyanna',
                'NISN_SISWA' => '121910693',
                'JENIS_KELAMIN' => 'P',
                'TEMPAT_TANGGAL_LAHIR' => 'Surabaya, 16 April 2012',
                'AGAMA' => 'Islam',
                'ANAK_KE' => '2',
                'STATUS_DALAM_KELUARGA' => 'Anak Kandung',
                'ALAMAT' => 'Jl Ketintang Baru 2 27',
                'TELEPON' => '',
                'FOTO' => '',
                'DITERIMA_DIKELAS' => 'SATU',
                'TANGGAL_DITERIMA_DIKELAS' => '2018-07-16',
            ),
            6 => 
            array (
                'NOMOR_INDUK' => '2293',
                'ID_ORTU' => 'WM007',
                'ID_SEKOLAH' => 'SCH0003',
                'NAMA_SISWA' => 'Anggabaya Athoillah',
                'NISN_SISWA' => '121169151',
                'JENIS_KELAMIN' => 'L',
                'TEMPAT_TANGGAL_LAHIR' => 'Sidoarjo, 25 Oktober 2011',
                'AGAMA' => 'Islam',
                'ANAK_KE' => '3',
                'STATUS_DALAM_KELUARGA' => 'Anak Kandung',
                'ALAMAT' => 'Jl Perak Tmr 260',
                'TELEPON' => '',
                'FOTO' => '',
                'DITERIMA_DIKELAS' => 'SATU',
                'TANGGAL_DITERIMA_DIKELAS' => '2018-07-16',
            ),
            7 => 
            array (
                'NOMOR_INDUK' => '2295',
                'ID_ORTU' => 'WM008',
                'ID_SEKOLAH' => 'SCH0002',
                'NAMA_SISWA' => 'Anindya Faras Radinia',
                'NISN_SISWA' => '128045194',
                'JENIS_KELAMIN' => 'P',
                'TEMPAT_TANGGAL_LAHIR' => 'Mojokerto, 28 Juli 2013',
                'AGAMA' => 'Islam',
                'ANAK_KE' => '2',
                'STATUS_DALAM_KELUARGA' => 'Anak Kandung',
                'ALAMAT' => 'Jl Tambaksari 14',
                'TELEPON' => '',
                'FOTO' => '',
                'DITERIMA_DIKELAS' => 'SATU',
                'TANGGAL_DITERIMA_DIKELAS' => '2018-07-16',
            ),
            8 => 
            array (
                'NOMOR_INDUK' => '2296',
                'ID_ORTU' => 'WM009',
                'ID_SEKOLAH' => 'SCH0001',
                'NAMA_SISWA' => 'Aqila Dinda Nur Fauziyyah',
                'NISN_SISWA' => '115143858',
                'JENIS_KELAMIN' => 'P',
                'TEMPAT_TANGGAL_LAHIR' => 'Sidoarjo, 13 Maret 2011',
                'AGAMA' => 'Islam',
                'ANAK_KE' => '1',
                'STATUS_DALAM_KELUARGA' => 'Anak Kandung',
                'ALAMAT' => 'Jl Indrapura 31',
                'TELEPON' => '',
                'FOTO' => '',
                'DITERIMA_DIKELAS' => 'SATU',
                'TANGGAL_DITERIMA_DIKELAS' => '2018-07-16',
            ),
            9 => 
            array (
                'NOMOR_INDUK' => '2300',
                'ID_ORTU' => 'WM010',
                'ID_SEKOLAH' => 'SCH0002',
                'NAMA_SISWA' => 'Athiyyah Nabila Faith Anwar',
                'NISN_SISWA' => '116563210',
                'JENIS_KELAMIN' => 'P',
                'TEMPAT_TANGGAL_LAHIR' => 'Bangkalan, 19 Januari 2012',
                'AGAMA' => 'Islam',
                'ANAK_KE' => '2',
                'STATUS_DALAM_KELUARGA' => 'Anak Kandung',
                'ALAMAT' => 'Jl Songoyudan 77',
                'TELEPON' => '',
                'FOTO' => '',
                'DITERIMA_DIKELAS' => 'SATU',
                'TANGGAL_DITERIMA_DIKELAS' => '2018-07-16',
            ),
            10 => 
            array (
                'NOMOR_INDUK' => '2303',
                'ID_ORTU' => 'WM011',
                'ID_SEKOLAH' => 'SCH0003',
                'NAMA_SISWA' => 'Az Zahra Syafiqah Waluyo',
                'NISN_SISWA' => '111405983',
                'JENIS_KELAMIN' => 'P',
                'TEMPAT_TANGGAL_LAHIR' => 'Surabaya, 30 Maret 2012',
                'AGAMA' => 'Islam',
                'ANAK_KE' => '3',
                'STATUS_DALAM_KELUARGA' => 'Anak Kandung',
                'ALAMAT' => 'Jl Jaksa Agung Suprapto 10',
                'TELEPON' => '',
                'FOTO' => '',
                'DITERIMA_DIKELAS' => 'SATU',
                'TANGGAL_DITERIMA_DIKELAS' => '2018-07-16',
            ),
            11 => 
            array (
                'NOMOR_INDUK' => '2306',
                'ID_ORTU' => 'WM012',
                'ID_SEKOLAH' => 'SCH0005',
                'NAMA_SISWA' => 'Bagas Ibrahim Al Ghifari',
                'NISN_SISWA' => '115167723',
                'JENIS_KELAMIN' => 'L',
                'TEMPAT_TANGGAL_LAHIR' => 'Malang, 23 Juli 2013',
                'AGAMA' => 'Islam',
                'ANAK_KE' => '2',
                'STATUS_DALAM_KELUARGA' => 'Anak Kandung',
                'ALAMAT' => 'Jl Dukuh Menanggal 124-126',
                'TELEPON' => '',
                'FOTO' => '',
                'DITERIMA_DIKELAS' => 'SATU',
                'TANGGAL_DITERIMA_DIKELAS' => '2018-07-16',
            ),
            12 => 
            array (
                'NOMOR_INDUK' => '2321',
                'ID_ORTU' => 'WM013',
                'ID_SEKOLAH' => 'SCH0004',
                'NAMA_SISWA' => 'Dzulfaida Firliana Zahra',
                'NISN_SISWA' => '127296936',
                'JENIS_KELAMIN' => 'P',
                'TEMPAT_TANGGAL_LAHIR' => 'Mojokerto, 15 April 2011',
                'AGAMA' => 'Islam',
                'ANAK_KE' => '1',
                'STATUS_DALAM_KELUARGA' => 'Anak Kandung',
                'ALAMAT' => 'Jl Luntas 31',
                'TELEPON' => '',
                'FOTO' => '',
                'DITERIMA_DIKELAS' => 'SATU',
                'TANGGAL_DITERIMA_DIKELAS' => '2018-07-16',
            ),
            13 => 
            array (
                'NOMOR_INDUK' => '2322',
                'ID_ORTU' => 'WM014',
                'ID_SEKOLAH' => 'SCH0003',
                'NAMA_SISWA' => 'Ellena Andres Tisya',
                'NISN_SISWA' => '117179695',
                'JENIS_KELAMIN' => 'P',
                'TEMPAT_TANGGAL_LAHIR' => 'Sumenep, 23 Mei 2012',
                'AGAMA' => 'Islam',
                'ANAK_KE' => '2',
                'STATUS_DALAM_KELUARGA' => 'Anak Kandung',
                'ALAMAT' => 'Jl Kedungdoro B-11/74',
                'TELEPON' => '',
                'FOTO' => '',
                'DITERIMA_DIKELAS' => 'SATU',
                'TANGGAL_DITERIMA_DIKELAS' => '2018-07-16',
            ),
            14 => 
            array (
                'NOMOR_INDUK' => '2323',
                'ID_ORTU' => 'WM015',
                'ID_SEKOLAH' => 'SCH0002',
                'NAMA_SISWA' => 'Fadhil Zaky Al Rizky Hermawan',
                'NISN_SISWA' => '121459498',
                'JENIS_KELAMIN' => 'L',
                'TEMPAT_TANGGAL_LAHIR' => 'Surabaya, 13 April 2013',
                'AGAMA' => 'Islam',
                'ANAK_KE' => '3',
                'STATUS_DALAM_KELUARGA' => 'Anak Kandung',
                'ALAMAT' => 'Jl Kalianak Tmr 179',
                'TELEPON' => '',
                'FOTO' => '',
                'DITERIMA_DIKELAS' => 'SATU',
                'TANGGAL_DITERIMA_DIKELAS' => '2018-07-16',
            ),
            15 => 
            array (
                'NOMOR_INDUK' => '2324',
                'ID_ORTU' => 'WM016',
                'ID_SEKOLAH' => 'SCH0001',
                'NAMA_SISWA' => 'Faiz Putra Sanjaya',
                'NISN_SISWA' => '124118968',
                'JENIS_KELAMIN' => 'L',
                'TEMPAT_TANGGAL_LAHIR' => 'Surabaya, 10 Januari 2011',
                'AGAMA' => 'Islam',
                'ANAK_KE' => '2',
                'STATUS_DALAM_KELUARGA' => 'Anak Kandung',
                'ALAMAT' => 'Jl Waspada 39 B Kav 20',
                'TELEPON' => '',
                'FOTO' => '',
                'DITERIMA_DIKELAS' => 'SATU',
                'TANGGAL_DITERIMA_DIKELAS' => '2018-07-16',
            ),
            16 => 
            array (
                'NOMOR_INDUK' => '2325',
                'ID_ORTU' => 'WM017',
                'ID_SEKOLAH' => 'SCH0002',
                'NAMA_SISWA' => 'Fakhrie Zhafran Khairy',
                'NISN_SISWA' => '114521635',
                'JENIS_KELAMIN' => 'L',
                'TEMPAT_TANGGAL_LAHIR' => 'Jember, 11 Maret 2012',
                'AGAMA' => 'Islam',
                'ANAK_KE' => '1',
                'STATUS_DALAM_KELUARGA' => 'Anak Kandung',
                'ALAMAT' => 'Jl Panggung III/23',
                'TELEPON' => '',
                'FOTO' => '',
                'DITERIMA_DIKELAS' => 'SATU',
                'TANGGAL_DITERIMA_DIKELAS' => '2018-07-16',
            ),
            17 => 
            array (
                'NOMOR_INDUK' => '2329',
                'ID_ORTU' => 'WM018',
                'ID_SEKOLAH' => 'SCH0003',
                'NAMA_SISWA' => 'Hafshah Jasmine Kamila',
                'NISN_SISWA' => '116429497',
                'JENIS_KELAMIN' => 'P',
                'TEMPAT_TANGGAL_LAHIR' => 'Surabaya, 21 Februari 2012',
                'AGAMA' => 'Islam',
                'ANAK_KE' => '2',
                'STATUS_DALAM_KELUARGA' => 'Anak Kandung',
                'ALAMAT' => 'Jl Mayjen Sungkono 236',
                'TELEPON' => '',
                'FOTO' => '',
                'DITERIMA_DIKELAS' => 'SATU',
                'TANGGAL_DITERIMA_DIKELAS' => '2018-07-16',
            ),
            18 => 
            array (
                'NOMOR_INDUK' => '2339',
                'ID_ORTU' => 'WM019',
                'ID_SEKOLAH' => 'SCH0004',
                'NAMA_SISWA' => 'Moch. Aqmal Keenand Faeyza Syaifullah',
                'NISN_SISWA' => '113513451',
                'JENIS_KELAMIN' => 'L',
                'TEMPAT_TANGGAL_LAHIR' => 'Mojokerto, 28 Agustus 2013',
                'AGAMA' => 'Islam',
                'ANAK_KE' => '3',
                'STATUS_DALAM_KELUARGA' => 'Anak Kandung',
                'ALAMAT' => 'Jl Jembatan Merah 15',
                'TELEPON' => '',
                'FOTO' => '',
                'DITERIMA_DIKELAS' => 'SATU',
                'TANGGAL_DITERIMA_DIKELAS' => '2018-07-16',
            ),
            19 => 
            array (
                'NOMOR_INDUK' => '2340',
                'ID_ORTU' => 'WM020',
                'ID_SEKOLAH' => 'SCH0005',
                'NAMA_SISWA' => 'Moch. Hizam Fadhil Assariy',
                'NISN_SISWA' => '114642159',
                'JENIS_KELAMIN' => 'L',
                'TEMPAT_TANGGAL_LAHIR' => 'Jombang, 10 Oktober 2011',
                'AGAMA' => 'Islam',
                'ANAK_KE' => '2',
                'STATUS_DALAM_KELUARGA' => 'Anak Kandung',
                'ALAMAT' => 'Kompl Permata Juanda B/83-85',
                'TELEPON' => '',
                'FOTO' => '',
                'DITERIMA_DIKELAS' => 'SATU',
                'TANGGAL_DITERIMA_DIKELAS' => '2018-07-16',
            ),
            20 => 
            array (
                'NOMOR_INDUK' => '2349',
                'ID_ORTU' => 'WM021',
                'ID_SEKOLAH' => 'SCH0004',
                'NAMA_SISWA' => 'Mutiara Firdasari Suwarno',
                'NISN_SISWA' => '118089068',
                'JENIS_KELAMIN' => 'P',
                'TEMPAT_TANGGAL_LAHIR' => 'Surabaya, 22 April 2011',
                'AGAMA' => 'Islam',
                'ANAK_KE' => '1',
                'STATUS_DALAM_KELUARGA' => 'Anak Kandung',
                'ALAMAT' => 'Jl Ketintang Baru 5 17',
                'TELEPON' => '',
                'FOTO' => '',
                'DITERIMA_DIKELAS' => 'SATU',
                'TANGGAL_DITERIMA_DIKELAS' => '2018-07-16',
            ),
            21 => 
            array (
                'NOMOR_INDUK' => '2350',
                'ID_ORTU' => 'WM022',
                'ID_SEKOLAH' => 'SCH0003',
                'NAMA_SISWA' => 'Nabiha Ghaliya Barandri',
                'NISN_SISWA' => '122016877',
                'JENIS_KELAMIN' => 'P',
                'TEMPAT_TANGGAL_LAHIR' => 'Surabaya, 14 Oktober 2013',
                'AGAMA' => 'Islam',
                'ANAK_KE' => '2',
                'STATUS_DALAM_KELUARGA' => 'Anak Kandung',
                'ALAMAT' => 'Jl Darmo Permai Tmr IV/18',
                'TELEPON' => '',
                'FOTO' => '',
                'DITERIMA_DIKELAS' => 'SATU',
                'TANGGAL_DITERIMA_DIKELAS' => '2018-07-16',
            ),
            22 => 
            array (
                'NOMOR_INDUK' => '2356',
                'ID_ORTU' => 'WM023',
                'ID_SEKOLAH' => 'SCH0002',
                'NAMA_SISWA' => 'Nadhiifa Ahnaf Banat Priawanda',
                'NISN_SISWA' => '111934853',
                'JENIS_KELAMIN' => 'P',
                'TEMPAT_TANGGAL_LAHIR' => 'Malang, 2 Mei 2011',
                'AGAMA' => 'Islam',
                'ANAK_KE' => '3',
                'STATUS_DALAM_KELUARGA' => 'Anak Kandung',
                'ALAMAT' => 'Jl Kapasan 41',
                'TELEPON' => '',
                'FOTO' => '',
                'DITERIMA_DIKELAS' => 'SATU',
                'TANGGAL_DITERIMA_DIKELAS' => '2018-07-16',
            ),
            23 => 
            array (
                'NOMOR_INDUK' => '2359',
                'ID_ORTU' => 'WM024',
                'ID_SEKOLAH' => 'SCH0001',
                'NAMA_SISWA' => 'Najwa Rayya Niandra Fadly',
                'NISN_SISWA' => '119184800',
                'JENIS_KELAMIN' => 'P',
                'TEMPAT_TANGGAL_LAHIR' => 'Bekasi, 26 Februari 2012',
                'AGAMA' => 'Islam',
                'ANAK_KE' => '2',
                'STATUS_DALAM_KELUARGA' => 'Anak Kandung',
                'ALAMAT' => 'Jl Raya Dukuh Kupang 139',
                'TELEPON' => '',
                'FOTO' => '',
                'DITERIMA_DIKELAS' => 'SATU',
                'TANGGAL_DITERIMA_DIKELAS' => '2018-07-16',
            ),
            24 => 
            array (
                'NOMOR_INDUK' => '2360',
                'ID_ORTU' => 'WM025',
                'ID_SEKOLAH' => 'SCH0002',
                'NAMA_SISWA' => 'Nararya Khaizuran Ammar',
                'NISN_SISWA' => '116132662',
                'JENIS_KELAMIN' => 'L',
                'TEMPAT_TANGGAL_LAHIR' => 'Bandung, 14 Desember 2011',
                'AGAMA' => 'Islam',
                'ANAK_KE' => '1',
                'STATUS_DALAM_KELUARGA' => 'Anak Kandung',
                'ALAMAT' => 'Jl Gayung Kebonsari 56',
                'TELEPON' => '',
                'FOTO' => '',
                'DITERIMA_DIKELAS' => 'SATU',
                'TANGGAL_DITERIMA_DIKELAS' => '2018-07-16',
            ),
            25 => 
            array (
                'NOMOR_INDUK' => '2362',
                'ID_ORTU' => 'WM026',
                'ID_SEKOLAH' => 'SCH0003',
                'NAMA_SISWA' => 'Nayla Rahmatil Izza',
                'NISN_SISWA' => '123035100',
                'JENIS_KELAMIN' => 'P',
                'TEMPAT_TANGGAL_LAHIR' => 'Surabaya, 22 Juni 2012',
                'AGAMA' => 'Islam',
                'ANAK_KE' => '2',
                'STATUS_DALAM_KELUARGA' => 'Anak Kandung',
                'ALAMAT' => 'Perum YKP PS Bl II-F/44',
                'TELEPON' => '',
                'FOTO' => '',
                'DITERIMA_DIKELAS' => 'SATU',
                'TANGGAL_DITERIMA_DIKELAS' => '2018-07-16',
            ),
            26 => 
            array (
                'NOMOR_INDUK' => '2363',
                'ID_ORTU' => 'WM027',
                'ID_SEKOLAH' => 'SCH0004',
                'NAMA_SISWA' => 'Noureen Umaiza Shanum',
                'NISN_SISWA' => '115884346',
                'JENIS_KELAMIN' => 'P',
                'TEMPAT_TANGGAL_LAHIR' => 'Surabaya, 13 Mei 2012',
                'AGAMA' => 'Islam',
                'ANAK_KE' => '3',
                'STATUS_DALAM_KELUARGA' => 'Anak Kandung',
                'ALAMAT' => 'Jl Rajawali 3',
                'TELEPON' => '',
                'FOTO' => '',
                'DITERIMA_DIKELAS' => 'SATU',
                'TANGGAL_DITERIMA_DIKELAS' => '2018-07-16',
            ),
            27 => 
            array (
                'NOMOR_INDUK' => '2367',
                'ID_ORTU' => 'WM028',
                'ID_SEKOLAH' => 'SCH0005',
                'NAMA_SISWA' => 'Razzan El-Fariza Yudhistira',
                'NISN_SISWA' => '114174848',
                'JENIS_KELAMIN' => 'L',
                'TEMPAT_TANGGAL_LAHIR' => 'Malang, 21 Juli 2011',
                'AGAMA' => 'Islam',
                'ANAK_KE' => '2',
                'STATUS_DALAM_KELUARGA' => 'Anak Kandung',
                'ALAMAT' => 'Jl Ikan Hiu 5',
                'TELEPON' => '',
                'FOTO' => '',
                'DITERIMA_DIKELAS' => 'SATU',
                'TANGGAL_DITERIMA_DIKELAS' => '2018-07-16',
            ),
            28 => 
            array (
                'NOMOR_INDUK' => '2369',
                'ID_ORTU' => 'WM029',
                'ID_SEKOLAH' => 'SCH0004',
                'NAMA_SISWA' => 'Rheisya Dwi Ardian Pradipa',
                'NISN_SISWA' => '118498936',
                'JENIS_KELAMIN' => 'P',
                'TEMPAT_TANGGAL_LAHIR' => 'Surabaya, 24 Juni 2011',
                'AGAMA' => 'Islam',
                'ANAK_KE' => '1',
                'STATUS_DALAM_KELUARGA' => 'Anak Kandung',
                'ALAMAT' => 'Jl Terumbu Karang 19',
                'TELEPON' => '',
                'FOTO' => '',
                'DITERIMA_DIKELAS' => 'SATU',
                'TANGGAL_DITERIMA_DIKELAS' => '2018-07-16',
            ),
            29 => 
            array (
                'NOMOR_INDUK' => '2375',
                'ID_ORTU' => 'WM030',
                'ID_SEKOLAH' => 'SCH0003',
                'NAMA_SISWA' => 'Teguh Surya Prakoso',
                'NISN_SISWA' => '122358428',
                'JENIS_KELAMIN' => 'L',
                'TEMPAT_TANGGAL_LAHIR' => 'Surabaya, 20 Agustus 2012',
                'AGAMA' => 'Islam',
                'ANAK_KE' => '2',
                'STATUS_DALAM_KELUARGA' => 'Anak Kandung',
                'ALAMAT' => 'Jl Mawar 66',
                'TELEPON' => '',
                'FOTO' => '',
                'DITERIMA_DIKELAS' => 'SATU',
                'TANGGAL_DITERIMA_DIKELAS' => '2018-07-16',
            ),
            30 => 
            array (
                'NOMOR_INDUK' => '2376',
                'ID_ORTU' => 'WM031',
                'ID_SEKOLAH' => 'SCH0001',
                'NAMA_SISWA' => 'Thoriq Muhammad Dzakky',
                'NISN_SISWA' => '124081397',
                'JENIS_KELAMIN' => 'L',
                'TEMPAT_TANGGAL_LAHIR' => 'Surabaya, 10 Desember 2012',
                'AGAMA' => 'Islam',
                'ANAK_KE' => '3',
                'STATUS_DALAM_KELUARGA' => 'Anak Kandung',
                'ALAMAT' => 'Jl Kalimas Baru 31 A',
                'TELEPON' => '',
                'FOTO' => '',
                'DITERIMA_DIKELAS' => 'SATU',
                'TANGGAL_DITERIMA_DIKELAS' => '2018-07-16',
            ),
            31 => 
            array (
                'NOMOR_INDUK' => '2377',
                'ID_ORTU' => 'WM032',
                'ID_SEKOLAH' => 'SCH0002',
                'NAMA_SISWA' => 'Tsalitsa Azqia Nairansyah',
                'NISN_SISWA' => '126956020',
                'JENIS_KELAMIN' => 'P',
                'TEMPAT_TANGGAL_LAHIR' => 'Surabaya, 20 September 2012',
                'AGAMA' => 'Islam',
                'ANAK_KE' => '2',
                'STATUS_DALAM_KELUARGA' => 'Anak Kandung',
                'ALAMAT' => 'Jl Undaan Kulon 45',
                'TELEPON' => '',
                'FOTO' => '',
                'DITERIMA_DIKELAS' => 'SATU',
                'TANGGAL_DITERIMA_DIKELAS' => '2018-07-16',
            ),
            32 => 
            array (
                'NOMOR_INDUK' => '2379',
                'ID_ORTU' => 'WM033',
                'ID_SEKOLAH' => 'SCH0003',
                'NAMA_SISWA' => 'Yusuf Rasyah Yuliawan',
                'NISN_SISWA' => '117443252',
                'JENIS_KELAMIN' => 'L',
                'TEMPAT_TANGGAL_LAHIR' => 'Sidoarjo, 18 April 2013',
                'AGAMA' => 'Islam',
                'ANAK_KE' => '1',
                'STATUS_DALAM_KELUARGA' => 'Anak Kandung',
                'ALAMAT' => 'Jl Raya Rungkut 5 Bl I/27',
                'TELEPON' => '',
                'FOTO' => '',
                'DITERIMA_DIKELAS' => 'SATU',
                'TANGGAL_DITERIMA_DIKELAS' => '2018-07-16',
            ),
            33 => 
            array (
                'NOMOR_INDUK' => '45',
                'ID_ORTU' => 'WM034',
                'ID_SEKOLAH' => 'SCH0004',
                'NAMA_SISWA' => 'Aisha Ailana Maritza Purwanto',
                'NISN_SISWA' => '289032',
                'JENIS_KELAMIN' => 'P',
                'TEMPAT_TANGGAL_LAHIR' => 'Surabaya, 16 November 2011',
                'AGAMA' => 'Islam',
                'ANAK_KE' => '2',
                'STATUS_DALAM_KELUARGA' => 'Anak Kandung',
                'ALAMAT' => 'Jl Kemayoran Baru 1',
                'TELEPON' => '',
                'FOTO' => '',
                'DITERIMA_DIKELAS' => 'DUA',
                'TANGGAL_DITERIMA_DIKELAS' => '2019-07-17',
            ),
            34 => 
            array (
                'NOMOR_INDUK' => '46',
                'ID_ORTU' => 'WM035',
                'ID_SEKOLAH' => 'SCH0005',
                'NAMA_SISWA' => 'Aldan',
                'NISN_SISWA' => '298033',
                'JENIS_KELAMIN' => 'L',
                'TEMPAT_TANGGAL_LAHIR' => 'Surabaya, 25 September 2012',
                'AGAMA' => 'Islam',
                'ANAK_KE' => '3',
                'STATUS_DALAM_KELUARGA' => 'Anak Kandung',
                'ALAMAT' => 'Jl Kembang Jepun 100',
                'TELEPON' => '',
                'FOTO' => '',
                'DITERIMA_DIKELAS' => 'DUA',
                'TANGGAL_DITERIMA_DIKELAS' => '2019-07-17',
            ),
        ));
        
        
    }
}