<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;

class WaliMuridTableSeeder extends Seeder
{

    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {
        

        \DB::table('wali_murid')->delete();
        
        \DB::table('wali_murid')->insert(array (
            0 => 
            array (
                'ID_ORTU' => 'WM001',
                'NAMA_AYAH' => 'Raden Prabowo',
                'NAMA_IBU' => 'Oni Kuswandari M.Ak',
                'ALAMAT_ORTU' => 'Gg. Sudirman No. 264, Surabaya 30573, Kalbar',
                'TELEPON_AYAH' => '4593574575377',
                'TELEPON_IBU' => '3119562852317',
                'PEKERJAAN_AYAH' => 'aut',
                'PEKERJAAN_IBU' => 'occaecati',
                'NAMA_WALI' => NULL,
                'ALAMAT_WALI' => NULL,
                'PEKERJAAN_WALI' => NULL,
            ),
            1 => 
            array (
                'ID_ORTU' => 'WM002',
                'NAMA_AYAH' => 'Estiono Zulkarnain S.IP',
                'NAMA_IBU' => 'Kayla Farida M.Ak',
                'ALAMAT_ORTU' => 'Ds. Perintis Kemerdekaan No. 542, Banjarmasin 68590, Malut',
                'TELEPON_AYAH' => '5623258888640',
                'TELEPON_IBU' => '7065876822629',
                'PEKERJAAN_AYAH' => 'voluptate',
                'PEKERJAAN_IBU' => 'accusamus',
                'NAMA_WALI' => NULL,
                'ALAMAT_WALI' => NULL,
                'PEKERJAAN_WALI' => NULL,
            ),
            2 => 
            array (
                'ID_ORTU' => 'WM003',
                'NAMA_AYAH' => 'Anom Gaiman Ardianto',
                'NAMA_IBU' => 'Cindy Kusmawati',
                'ALAMAT_ORTU' => 'Ds. Ters. Buah Batu No. 300, Padang 10753, NTT',
                'TELEPON_AYAH' => '6142855953306',
                'TELEPON_IBU' => '1215074239799',
                'PEKERJAAN_AYAH' => 'ab',
                'PEKERJAAN_IBU' => 'deserunt',
                'NAMA_WALI' => NULL,
                'ALAMAT_WALI' => NULL,
                'PEKERJAAN_WALI' => NULL,
            ),
            3 => 
            array (
                'ID_ORTU' => 'WM004',
                'NAMA_AYAH' => 'Drajat Dodo Budiman S.IP',
                'NAMA_IBU' => 'Nilam Kusmawati M.Farm',
                'ALAMAT_ORTU' => 'Gg. Dr. Junjunan No. 996, Palembang 18584, Bengkulu',
                'TELEPON_AYAH' => '7265180492533',
                'TELEPON_IBU' => '3443292253852',
                'PEKERJAAN_AYAH' => 'consequatur',
                'PEKERJAAN_IBU' => 'aut',
                'NAMA_WALI' => NULL,
                'ALAMAT_WALI' => NULL,
                'PEKERJAAN_WALI' => NULL,
            ),
            4 => 
            array (
                'ID_ORTU' => 'WM005',
                'NAMA_AYAH' => 'Laksana Martaka Sitorus M.Kom.',
                'NAMA_IBU' => 'Zelda Puput Wastuti S.IP',
                'ALAMAT_ORTU' => 'Gg. Salatiga No. 840, Solok 50865, Sumbar',
                'TELEPON_AYAH' => '6853379659925',
                'TELEPON_IBU' => '8806481552217',
                'PEKERJAAN_AYAH' => 'aut',
                'PEKERJAAN_IBU' => 'id',
                'NAMA_WALI' => NULL,
                'ALAMAT_WALI' => NULL,
                'PEKERJAAN_WALI' => NULL,
            ),
            5 => 
            array (
                'ID_ORTU' => 'WM006',
                'NAMA_AYAH' => 'Tomi Raden Mustofa S.Farm',
                'NAMA_IBU' => 'Patricia Suartini',
                'ALAMAT_ORTU' => 'Jln. Lada No. 514, Bogor 21038, Pabar',
                'TELEPON_AYAH' => '9738833699883',
                'TELEPON_IBU' => '8288808968976',
                'PEKERJAAN_AYAH' => 'quam',
                'PEKERJAAN_IBU' => 'odit',
                'NAMA_WALI' => NULL,
                'ALAMAT_WALI' => NULL,
                'PEKERJAAN_WALI' => NULL,
            ),
            6 => 
            array (
                'ID_ORTU' => 'WM007',
                'NAMA_AYAH' => 'Harimurti Umay Gunarto',
                'NAMA_IBU' => 'Ajeng Palastri',
                'ALAMAT_ORTU' => 'Psr. Basudewo No. 434, Solok 60663, DIY',
                'TELEPON_AYAH' => '2238149235650',
                'TELEPON_IBU' => '3098034989354',
                'PEKERJAAN_AYAH' => 'architecto',
                'PEKERJAAN_IBU' => 'cum',
                'NAMA_WALI' => NULL,
                'ALAMAT_WALI' => NULL,
                'PEKERJAAN_WALI' => NULL,
            ),
            7 => 
            array (
                'ID_ORTU' => 'WM008',
                'NAMA_AYAH' => 'Asirwada Budiman',
                'NAMA_IBU' => 'Kayla Tiara Mandasari',
                'ALAMAT_ORTU' => 'Dk. Bara Tambar No. 670, Bogor 87756, Banten',
                'TELEPON_AYAH' => '4395537815621',
                'TELEPON_IBU' => '1747676762072',
                'PEKERJAAN_AYAH' => 'similique',
                'PEKERJAAN_IBU' => 'provident',
                'NAMA_WALI' => NULL,
                'ALAMAT_WALI' => NULL,
                'PEKERJAAN_WALI' => NULL,
            ),
            8 => 
            array (
                'ID_ORTU' => 'WM009',
                'NAMA_AYAH' => 'Jais Sihombing S.IP',
                'NAMA_IBU' => 'Siti Yolanda',
                'ALAMAT_ORTU' => 'Kpg. Gambang No. 946, Yogyakarta 10774, Sumut',
                'TELEPON_AYAH' => '6992933455645',
                'TELEPON_IBU' => '3558722158315',
                'PEKERJAAN_AYAH' => 'dolor',
                'PEKERJAAN_IBU' => 'aut',
                'NAMA_WALI' => NULL,
                'ALAMAT_WALI' => NULL,
                'PEKERJAAN_WALI' => NULL,
            ),
            9 => 
            array (
                'ID_ORTU' => 'WM010',
                'NAMA_AYAH' => 'Purwanto Irawan',
                'NAMA_IBU' => 'Rina Pertiwi',
                'ALAMAT_ORTU' => 'Dk. Bayan No. 505, Prabumulih 11573, Kepri',
                'TELEPON_AYAH' => '3436769003912',
                'TELEPON_IBU' => '1859276940323',
                'PEKERJAAN_AYAH' => 'dolore',
                'PEKERJAAN_IBU' => 'debitis',
                'NAMA_WALI' => NULL,
                'ALAMAT_WALI' => NULL,
                'PEKERJAAN_WALI' => NULL,
            ),
            10 => 
            array (
                'ID_ORTU' => 'WM011',
                'NAMA_AYAH' => 'Taswir Bakiono Simanjuntak',
                'NAMA_IBU' => 'Cindy Mulyani',
                'ALAMAT_ORTU' => 'Jr. Baja Raya No. 967, Binjai 67476, Jambi',
                'TELEPON_AYAH' => '7278637746856',
                'TELEPON_IBU' => '8009276376928',
                'PEKERJAAN_AYAH' => 'nulla',
                'PEKERJAAN_IBU' => 'natus',
                'NAMA_WALI' => NULL,
                'ALAMAT_WALI' => NULL,
                'PEKERJAAN_WALI' => NULL,
            ),
            11 => 
            array (
                'ID_ORTU' => 'WM012',
                'NAMA_AYAH' => 'Sakti Umar Saptono M.Farm',
                'NAMA_IBU' => 'Novi Mandasari',
                'ALAMAT_ORTU' => 'Jln. Imam No. 481, Tarakan 92618, Banten',
                'TELEPON_AYAH' => '6402166268477',
                'TELEPON_IBU' => '4581005185734',
                'PEKERJAAN_AYAH' => 'sit',
                'PEKERJAAN_IBU' => 'alias',
                'NAMA_WALI' => NULL,
                'ALAMAT_WALI' => NULL,
                'PEKERJAAN_WALI' => NULL,
            ),
            12 => 
            array (
                'ID_ORTU' => 'WM013',
                'NAMA_AYAH' => 'Darmana Prayitna Hidayat S.Pt',
                'NAMA_IBU' => 'Jane Hariyah M.Farm',
                'ALAMAT_ORTU' => 'Gg. Elang No. 795, Salatiga 74850, Sulut',
                'TELEPON_AYAH' => '1948209790509',
                'TELEPON_IBU' => '4602557017293',
                'PEKERJAAN_AYAH' => 'ut',
                'PEKERJAAN_IBU' => 'eaque',
                'NAMA_WALI' => NULL,
                'ALAMAT_WALI' => NULL,
                'PEKERJAAN_WALI' => NULL,
            ),
            13 => 
            array (
                'ID_ORTU' => 'WM014',
                'NAMA_AYAH' => 'Indra Dongoran',
                'NAMA_IBU' => 'Puji Melinda Winarsih',
                'ALAMAT_ORTU' => 'Psr. Lembong No. 703, Kediri 75132, Sultra',
                'TELEPON_AYAH' => '2912125264263',
                'TELEPON_IBU' => '5584567228304',
                'PEKERJAAN_AYAH' => 'iure',
                'PEKERJAAN_IBU' => 'est',
                'NAMA_WALI' => NULL,
                'ALAMAT_WALI' => NULL,
                'PEKERJAAN_WALI' => NULL,
            ),
            14 => 
            array (
                'ID_ORTU' => 'WM015',
                'NAMA_AYAH' => 'Elon Budiman S.Kom',
                'NAMA_IBU' => 'Hana Irma Padmasari S.Pd',
                'ALAMAT_ORTU' => 'Jln. Sutarto No. 945, Sungai Penuh 24157, Aceh',
                'TELEPON_AYAH' => '5079510958901',
                'TELEPON_IBU' => '5473115275457',
                'PEKERJAAN_AYAH' => 'eum',
                'PEKERJAAN_IBU' => 'quia',
                'NAMA_WALI' => NULL,
                'ALAMAT_WALI' => NULL,
                'PEKERJAAN_WALI' => NULL,
            ),
            15 => 
            array (
                'ID_ORTU' => 'WM016',
                'NAMA_AYAH' => 'Karman Natsir',
                'NAMA_IBU' => 'Vera Safitri',
                'ALAMAT_ORTU' => 'Kpg. Bakhita No. 377, Pontianak 31851, Lampung',
                'TELEPON_AYAH' => '2303377910434',
                'TELEPON_IBU' => '5674689538650',
                'PEKERJAAN_AYAH' => 'nesciunt',
                'PEKERJAAN_IBU' => 'voluptatem',
                'NAMA_WALI' => NULL,
                'ALAMAT_WALI' => NULL,
                'PEKERJAAN_WALI' => NULL,
            ),
            16 => 
            array (
                'ID_ORTU' => 'WM017',
                'NAMA_AYAH' => 'Karma Haryanto',
                'NAMA_IBU' => 'Jasmin Hariyah',
                'ALAMAT_ORTU' => 'Kpg. Cikutra Timur No. 429, Tomohon 88700, Kepri',
                'TELEPON_AYAH' => '8913762594989',
                'TELEPON_IBU' => '2495580849725',
                'PEKERJAAN_AYAH' => 'modi',
                'PEKERJAAN_IBU' => 'qui',
                'NAMA_WALI' => NULL,
                'ALAMAT_WALI' => NULL,
                'PEKERJAAN_WALI' => NULL,
            ),
            17 => 
            array (
                'ID_ORTU' => 'WM018',
                'NAMA_AYAH' => 'Wage Hidayanto',
                'NAMA_IBU' => 'Tiara Diana Melani S.H.',
                'ALAMAT_ORTU' => 'Ds. Jayawijaya No. 931, Tangerang Selatan 64295, Banten',
                'TELEPON_AYAH' => '4470562773873',
                'TELEPON_IBU' => '3396725836283',
                'PEKERJAAN_AYAH' => 'deleniti',
                'PEKERJAAN_IBU' => 'ut',
                'NAMA_WALI' => NULL,
                'ALAMAT_WALI' => NULL,
                'PEKERJAAN_WALI' => NULL,
            ),
            18 => 
            array (
                'ID_ORTU' => 'WM019',
                'NAMA_AYAH' => 'Daliono Karja Mahendra',
                'NAMA_IBU' => 'Nadia Agnes Nurdiyanti',
                'ALAMAT_ORTU' => 'Kpg. Rajawali Barat No. 331, Palangka Raya 55489, Kalbar',
                'TELEPON_AYAH' => '2216652942718',
                'TELEPON_IBU' => '5091610411570',
                'PEKERJAAN_AYAH' => 'ratione',
                'PEKERJAAN_IBU' => 'atque',
                'NAMA_WALI' => NULL,
                'ALAMAT_WALI' => NULL,
                'PEKERJAAN_WALI' => NULL,
            ),
            19 => 
            array (
                'ID_ORTU' => 'WM020',
                'NAMA_AYAH' => 'Muni Jamil Waluyo M.TI.',
                'NAMA_IBU' => 'Yance Laksita',
                'ALAMAT_ORTU' => 'Gg. Katamso No. 257, Bogor 53850, Sumbar',
                'TELEPON_AYAH' => '7625037998486',
                'TELEPON_IBU' => '4732247196427',
                'PEKERJAAN_AYAH' => 'tenetur',
                'PEKERJAAN_IBU' => 'id',
                'NAMA_WALI' => NULL,
                'ALAMAT_WALI' => NULL,
                'PEKERJAAN_WALI' => NULL,
            ),
            20 => 
            array (
                'ID_ORTU' => 'WM021',
                'NAMA_AYAH' => 'Cawisono Adriansyah',
                'NAMA_IBU' => 'Agnes Hassanah',
                'ALAMAT_ORTU' => 'Jln. Panjaitan No. 188, Lhokseumawe 69132, DKI',
                'TELEPON_AYAH' => '7915654853383',
                'TELEPON_IBU' => '5454997146026',
                'PEKERJAAN_AYAH' => 'perferendis',
                'PEKERJAAN_IBU' => 'assumenda',
                'NAMA_WALI' => NULL,
                'ALAMAT_WALI' => NULL,
                'PEKERJAAN_WALI' => NULL,
            ),
            21 => 
            array (
                'ID_ORTU' => 'WM022',
                'NAMA_AYAH' => 'Hardi Banara Sinaga',
                'NAMA_IBU' => 'Winda Kusmawati S.IP',
                'ALAMAT_ORTU' => 'Jln. Jend. Sudirman No. 893, Surabaya 21636, Malut',
                'TELEPON_AYAH' => '5389626316181',
                'TELEPON_IBU' => '1712567362160',
                'PEKERJAAN_AYAH' => 'et',
                'PEKERJAAN_IBU' => 'vel',
                'NAMA_WALI' => NULL,
                'ALAMAT_WALI' => NULL,
                'PEKERJAAN_WALI' => NULL,
            ),
            22 => 
            array (
                'ID_ORTU' => 'WM023',
                'NAMA_AYAH' => 'Cayadi Cahya Narpati S.Farm',
                'NAMA_IBU' => 'Zaenab Riyanti',
                'ALAMAT_ORTU' => 'Jln. Jambu No. 570, Tangerang 17065, Sumbar',
                'TELEPON_AYAH' => '6530588954814',
                'TELEPON_IBU' => '8137380149499',
                'PEKERJAAN_AYAH' => 'nisi',
                'PEKERJAAN_IBU' => 'voluptate',
                'NAMA_WALI' => NULL,
                'ALAMAT_WALI' => NULL,
                'PEKERJAAN_WALI' => NULL,
            ),
            23 => 
            array (
                'ID_ORTU' => 'WM024',
                'NAMA_AYAH' => 'Wisnu Siregar',
                'NAMA_IBU' => 'Usyi Halimah',
                'ALAMAT_ORTU' => 'Psr. Basudewo No. 706, Sorong 82159, Jambi',
                'TELEPON_AYAH' => '8938080594747',
                'TELEPON_IBU' => '5536179206821',
                'PEKERJAAN_AYAH' => 'tempora',
                'PEKERJAAN_IBU' => 'quae',
                'NAMA_WALI' => NULL,
                'ALAMAT_WALI' => NULL,
                'PEKERJAAN_WALI' => NULL,
            ),
            24 => 
            array (
                'ID_ORTU' => 'WM025',
                'NAMA_AYAH' => 'Darmaji Jayadi Rajasa S.Farm',
                'NAMA_IBU' => 'Rini Lailasari',
                'ALAMAT_ORTU' => 'Ds. Gajah No. 662, Bandung 17714, Kalbar',
                'TELEPON_AYAH' => '7091876937771',
                'TELEPON_IBU' => '8890955035601',
                'PEKERJAAN_AYAH' => 'dignissimos',
                'PEKERJAAN_IBU' => 'sed',
                'NAMA_WALI' => NULL,
                'ALAMAT_WALI' => NULL,
                'PEKERJAAN_WALI' => NULL,
            ),
            25 => 
            array (
                'ID_ORTU' => 'WM026',
                'NAMA_AYAH' => 'Raden Kajen Prayoga S.Sos',
                'NAMA_IBU' => 'Jane Widiastuti',
                'ALAMAT_ORTU' => 'Ds. Sutami No. 507, Tangerang Selatan 64845, Jateng',
                'TELEPON_AYAH' => '4542797185944',
                'TELEPON_IBU' => '8558212300242',
                'PEKERJAAN_AYAH' => 'a',
                'PEKERJAAN_IBU' => 'totam',
                'NAMA_WALI' => NULL,
                'ALAMAT_WALI' => NULL,
                'PEKERJAAN_WALI' => NULL,
            ),
            26 => 
            array (
                'ID_ORTU' => 'WM027',
                'NAMA_AYAH' => 'Hardi Banawi Haryanto',
                'NAMA_IBU' => 'Jelita Pudjiastuti M.Pd',
                'ALAMAT_ORTU' => 'Ki. Bara No. 712, Solok 22765, Riau',
                'TELEPON_AYAH' => '8142719328859',
                'TELEPON_IBU' => '5316836733162',
                'PEKERJAAN_AYAH' => 'tenetur',
                'PEKERJAAN_IBU' => 'eveniet',
                'NAMA_WALI' => NULL,
                'ALAMAT_WALI' => NULL,
                'PEKERJAAN_WALI' => NULL,
            ),
            27 => 
            array (
                'ID_ORTU' => 'WM028',
                'NAMA_AYAH' => 'Gading Simanjuntak',
                'NAMA_IBU' => 'Gawati Agustina',
                'ALAMAT_ORTU' => 'Ds. Dipatiukur No. 31, Pekalongan 54769, Malut',
                'TELEPON_AYAH' => '1468377307347',
                'TELEPON_IBU' => '5657661150065',
                'PEKERJAAN_AYAH' => 'et',
                'PEKERJAAN_IBU' => 'ex',
                'NAMA_WALI' => NULL,
                'ALAMAT_WALI' => NULL,
                'PEKERJAAN_WALI' => NULL,
            ),
            28 => 
            array (
                'ID_ORTU' => 'WM029',
                'NAMA_AYAH' => 'Karna Hutagalung M.M.',
                'NAMA_IBU' => 'Yessi Puspasari',
                'ALAMAT_ORTU' => 'Ds. Sukabumi No. 862, Sabang 59159, Kalbar',
                'TELEPON_AYAH' => '2317976371335',
                'TELEPON_IBU' => '6629065083473',
                'PEKERJAAN_AYAH' => 'minus',
                'PEKERJAAN_IBU' => 'aut',
                'NAMA_WALI' => NULL,
                'ALAMAT_WALI' => NULL,
                'PEKERJAAN_WALI' => NULL,
            ),
            29 => 
            array (
                'ID_ORTU' => 'WM030',
                'NAMA_AYAH' => 'Lutfan Wibisono',
                'NAMA_IBU' => 'Ulya Utami',
                'ALAMAT_ORTU' => 'Jln. Sudirman No. 799, Binjai 46623, Malut',
                'TELEPON_AYAH' => '4086293307347',
                'TELEPON_IBU' => '8566687231940',
                'PEKERJAAN_AYAH' => 'et',
                'PEKERJAAN_IBU' => 'velit',
                'NAMA_WALI' => NULL,
                'ALAMAT_WALI' => NULL,
                'PEKERJAAN_WALI' => NULL,
            ),
            30 => 
            array (
                'ID_ORTU' => 'WM031',
                'NAMA_AYAH' => 'Dwi Harjo Megantara',
                'NAMA_IBU' => 'Padmi Mala Novitasari',
                'ALAMAT_ORTU' => 'Gg. Baabur Royan No. 38, Tarakan 53746, Jabar',
                'TELEPON_AYAH' => '9807054522074',
                'TELEPON_IBU' => '7072972600419',
                'PEKERJAAN_AYAH' => 'amet',
                'PEKERJAAN_IBU' => 'eveniet',
                'NAMA_WALI' => NULL,
                'ALAMAT_WALI' => NULL,
                'PEKERJAAN_WALI' => NULL,
            ),
            31 => 
            array (
                'ID_ORTU' => 'WM032',
                'NAMA_AYAH' => 'Hartana Wibowo',
                'NAMA_IBU' => 'Karen Hassanah',
                'ALAMAT_ORTU' => 'Kpg. Achmad Yani No. 286, Administrasi Jakarta Selatan 66783, Kaltara',
                'TELEPON_AYAH' => '7022940076827',
                'TELEPON_IBU' => '7035178014816',
                'PEKERJAAN_AYAH' => 'ut',
                'PEKERJAAN_IBU' => 'aut',
                'NAMA_WALI' => NULL,
                'ALAMAT_WALI' => NULL,
                'PEKERJAAN_WALI' => NULL,
            ),
            32 => 
            array (
                'ID_ORTU' => 'WM033',
                'NAMA_AYAH' => 'Luhung Siregar S.E.I',
                'NAMA_IBU' => 'Kayla Utami',
                'ALAMAT_ORTU' => 'Ds. Asia Afrika No. 227, Semarang 30014, Lampung',
                'TELEPON_AYAH' => '1890151691004',
                'TELEPON_IBU' => '1206617103983',
                'PEKERJAAN_AYAH' => 'numquam',
                'PEKERJAAN_IBU' => 'impedit',
                'NAMA_WALI' => NULL,
                'ALAMAT_WALI' => NULL,
                'PEKERJAAN_WALI' => NULL,
            ),
            33 => 
            array (
                'ID_ORTU' => 'WM034',
                'NAMA_AYAH' => 'Limar Santoso',
                'NAMA_IBU' => 'Cinthia Sari Uyainah M.Pd',
                'ALAMAT_ORTU' => 'Jr. Baranang Siang Indah No. 784, Kendari 58553, Sultra',
                'TELEPON_AYAH' => '3004450267637',
                'TELEPON_IBU' => '1812200967101',
                'PEKERJAAN_AYAH' => 'adipisci',
                'PEKERJAAN_IBU' => 'sit',
                'NAMA_WALI' => NULL,
                'ALAMAT_WALI' => NULL,
                'PEKERJAAN_WALI' => NULL,
            ),
            34 => 
            array (
                'ID_ORTU' => 'WM035',
                'NAMA_AYAH' => 'Jarwa Tirta Pangestu',
                'NAMA_IBU' => 'Puti Ira Wijayanti M.Pd',
                'ALAMAT_ORTU' => 'Jln. Merdeka No. 869, Langsa 57379, Maluku',
                'TELEPON_AYAH' => '2215443219775',
                'TELEPON_IBU' => '8102755972692',
                'PEKERJAAN_AYAH' => 'quae',
                'PEKERJAAN_IBU' => 'hic',
                'NAMA_WALI' => NULL,
                'ALAMAT_WALI' => NULL,
                'PEKERJAAN_WALI' => NULL,
            ),
        ));
        
        
    }
}